"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ErrorCodes = void 0;
exports.ErrorCodes = {
    AUTH_EMAIL_TAKEN: "AUTH_EMAIL_TAKEN",
    AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
    AUTH_SESSION_EXPIRED: "AUTH_SESSION_EXPIRED",
    AUTH_USER_DISABLED: "AUTH_USER_DISABLED",
    CSRF_INVALID: "CSRF_INVALID",
    DONGLE_NOT_FOUND: "DONGLE_NOT_FOUND",
    DONGLE_OWNED_BY_OTHER: "DONGLE_OWNED_BY_OTHER",
    AGENT_OFFLINE: "AGENT_OFFLINE",
    PAIRING_SESSION_INVALID: "PAIRING_SESSION_INVALID",
    PAIRING_SESSION_EXPIRED: "PAIRING_SESSION_EXPIRED",
    PAIRING_PIN_INVALID: "PAIRING_PIN_INVALID",
    PAIRING_SECURITY_HOLD: "PAIRING_SECURITY_HOLD",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    NOT_FOUND: "NOT_FOUND",
    PASSWORD_RESET_EXPIRED: "PASSWORD_RESET_EXPIRED",
    PASSWORD_RESET_INVALID: "PASSWORD_RESET_INVALID",
    RATE_LIMITED: "RATE_LIMITED",
    VALIDATION_ERROR: "VALIDATION_ERROR",
};
